baseURL = "https://amlcs.herokuapp.com/"
languageCode = "en-us"
title = "AML-CS"

[params]
# description = "Applied Math and Computer Science Laboratory (AML-CS) at Universidad del Norte in Barranquilla"
logoimage = "images/logo.jpg"
copyright = "Universidad del Norte, Colombia."

# mathjax = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
## Uncomment if you want mathjax enabled. The above cdn source is taken from https://gohugo.io/content-management/formats/#mathjax-with-hugo   


[permalinks]
blog  = "/blog/:year/:month/:title/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

# [[menu.main]]
# weight = 4
# name = "More items"
# url = "/more/"
# identifier = "more"
#   [[menu.main]]
#   parent = "more"
#   weight = 1
#   name = "Some more menu"
#   url = "/more/some-more-menu/"
#   [[menu.main]]
#   parent = "more"
#   weight = 2
#   name = "items to show"
#   url = "/more/items-to-show/"
#   [[menu.main]]
#   parent = "more"
#   weight = 3
#   name = "the nested menus feature"
#   url = "/more/the-nested-menus-feature/"

[[menu.main]]
weight = 2
name = "Posts"
url = "/posts/"

[[menu.main]]
weight = 3
name = "Current Students"
url = "/current-students/"

[[menu.main]]
weight = 4
name = "Former Students"
url = "/former-students/"

[[menu.main]]
weight = 5
name = "Publications"
url = "/publications/"
