baseURL = "https://aml-cs.github.io/"
languageCode = "en-us"
title = "AML-CS | Uninorte"

[params]
description = "Applied Math and Computer Science Laboratory (AML-CS) at Universidad del Norte in Barranquilla"
logoimage = "images/logo.jpg"
logourl = "https://aml-cs.github.io/images/logo.jpg"
copyright = "Universidad del Norte, Colombia."

[permalinks]
blog  = "/blog/:year/:month/:title/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Posts"
url = "/posts/"

[[menu.main]]
weight = 3
name = "Talks"
url = "/talks/"
identifier = "talks"
  [[menu.main]]
  parent = "talks"
  weight = 1
  name = "Talk Series"
  url = "/talks/talk-series/"
  [[menu.main]]
  parent = "talks"
  weight = 2
  name = "Talks by Dr. Elias Nino-Ruiz"
  url = "/talks/elias-niño/"

[[menu.main]]
weight = 4
name = "Events"
url = "/events/"
identifier = "events"
  [[menu.main]]
  parent = "events"
  weight = 1
  name = "3rd International Workshop on Data Assimilation"
  url = "/events/3rd-international-da-workshop/"

[[menu.main]]
weight = 5
name = "Call for Papers"
url = "/call-for-papers/"
identifier = "call-for-papers"
  [[menu.main]]
  parent = "call-for-papers"
  weight = 1
  name = "Special Issue of IJAI - 2022"
  url = "/call-for-papers/ijai-2022/"

[[menu.main]]
weight = 6
name = "Current Students"
url = "/current-students/"

[[menu.main]]
weight = 7
name = "Former Students"
url = "/former-students/"

[[menu.main]]
weight = 8
name = "Publications"
url = "/publications/"

[[menu.main]]
weight = 9
name = "Awards"
url = "/awards/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 2

[markup.goldmark.renderer]
  unsafe= true